# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle

default:
  tags:
    - asprunner   # set tag globally to select shared runners

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  tags:
    - asprunner
  stage: build
  script: |
    apt update && apt install -y gcc libpython3-dev python3.12-venv
    python3 -m venv ~/.virtualenvs/cpg
    source ~/.virtualenvs/cpg/bin/activate
    pip3 install jep
    ./gradlew build
  artifacts:
    paths:
      - app/build/reports/tests
    when: always
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
