/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-test-fixtures`
    id("buildlogic.kotlin-application-conventions")
    id("org.jetbrains.kotlin.plugin.serialization") version "1.4.20"
}

dependencies {
    implementation(kotlin("reflect"))

    api(libs.bundles.cpg) { isChanging = true }
    api(libs.jep)

    implementation("com.charleskorn.kaml:kaml:0.67.0")
    // implementation("com.github.ajalt.clikt:clikt:5.0.2")

    testFixturesApi(kotlin("test-junit5"))
}

application {
    // Define the main class for the application.
    mainClass = "de.fraunhofer.aisec.openstack.CheckerKt"
}
