/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins { id("buildlogic.kotlin-library-conventions") }

dependencies {
    implementation(libs.jep)
    api(project(":codyze-evaluator"))
    api(project(":codyze-query-catalog"))

    testImplementation(testFixtures(project(":codyze-evaluator")))
}
